### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by digoal** [zfsonlinux/spl#490]
```
#yum install -y zfs
Loaded plugins: branch, fastestmirror, security
Loading mirror speeds from cached hostfile
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package zfs.x86_64 0:0.6.5.3-1.el6 will be installed
--> Processing Dependency: zfs-kmod = 0.6.5.3 for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: spl = 0.6.5.3 for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libzpool2 = 0.6.5.3 for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libzfs2 = 0.6.5.3 for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libuutil1 = 0.6.5.3 for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libnvpair1 = 0.6.5.3 for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libzpool.so.2()(64bit) for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libzfs_core.so.1()(64bit) for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libzfs.so.2()(64bit) for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libuutil.so.1()(64bit) for package: zfs-0.6.5.3-1.el6.x86_64
--> Processing Dependency: libnvpair.so.1()(64bit) for package: zfs-0.6.5.3-1.el6.x86_64
--> Running transaction check
---> Package libnvpair1.x86_64 0:0.6.5.3-1.el6 will be installed
---> Package libuutil1.x86_64 0:0.6.5.3-1.el6 will be installed
---> Package libzfs2.x86_64 0:0.6.5.3-1.el6 will be installed
---> Package libzpool2.x86_64 0:0.6.5.3-1.el6 will be installed
---> Package spl.x86_64 0:0.6.5.3-1.el6 will be installed
--> Processing Dependency: spl-kmod = 0.6.5.3 for package: spl-0.6.5.3-1.el6.x86_64
---> Package zfs-dkms.noarch 0:0.6.5.3-1.el6 will be installed
--> Processing Dependency: dkms >= 2.2.0.3-20 for package: zfs-dkms-0.6.5.3-1.el6.noarch
--> Running transaction check
---> Package dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el6 will be installed
---> Package spl-dkms.noarch 0:0.6.5.3-1.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================================================================================
 Package                                                 Arch                                                Version                                                                 Repository                                         Size
=============================================================================================================================================================================================================================================
Installing:
 zfs                                                     x86_64                                              0.6.5.3-1.el6                                                           zfs                                               324 k
Installing for dependencies:
 dkms                                                    noarch                                              2.2.0.3-30.git.7c3e7c5.el6                                              epel                                               77 k
 libnvpair1                                              x86_64                                              0.6.5.3-1.el6                                                           zfs                                                28 k
 libuutil1                                               x86_64                                              0.6.5.3-1.el6                                                           zfs                                                33 k
 libzfs2                                                 x86_64                                              0.6.5.3-1.el6                                                           zfs                                               113 k
 libzpool2                                               x86_64                                              0.6.5.3-1.el6                                                           zfs                                               401 k
 spl                                                     x86_64                                              0.6.5.3-1.el6                                                           zfs                                                25 k
 spl-dkms                                                noarch                                              0.6.5.3-1.el6                                                           zfs                                               449 k
 zfs-dkms                                                noarch                                              0.6.5.3-1.el6                                                           zfs                                               1.9 M

Transaction Summary
=============================================================================================================================================================================================================================================
Install       9 Package(s)

Total size: 3.3 M
Total download size: 449 k
Installed size: 16 M
Downloading Packages:
spl-dkms-0.6.5.3-1.el6.noarch.rpm                                                                                                                                                                                     | 449 kB     00:01     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.
  Installing : libuutil1-0.6.5.3-1.el6.x86_64                                                                                                                                                                                            1/9 
  Installing : libnvpair1-0.6.5.3-1.el6.x86_64                                                                                                                                                                                           2/9 
  Installing : libzpool2-0.6.5.3-1.el6.x86_64                                                                                                                                                                                            3/9 
  Installing : dkms-2.2.0.3-30.git.7c3e7c5.el6.noarch                                                                                                                                                                                    4/9 
  Installing : spl-dkms-0.6.5.3-1.el6.noarch                                                                                                                                                                                             5/9 
Non-fatal POSTIN scriptlet failure in rpm package spl-dkms-0.6.5.3-1.el6.noarch
Loading new spl-0.6.5.3 DKMS files...
Building for 2.6.32-358.23.2.ali1195.el6.x86_64
Building initial module for 2.6.32-358.23.2.ali1195.el6.x86_64
Error! Bad return status for module build on kernel: 2.6.32-358.23.2.ali1195.el6.x86_64 (x86_64)
Consult /var/lib/dkms/spl/0.6.5.3/build/make.log for more information.
warning: %post(spl-dkms-0.6.5.3-1.el6.noarch) scriptlet failed, exit status 10
  Installing : zfs-dkms-0.6.5.3-1.el6.noarch                                                                                                                                                                                             6/9 

Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms-0.6.5.3-1.el6.noarch
Loading new zfs-0.6.5.3 DKMS files...
Building for 2.6.32-358.23.2.ali1195.el6.x86_64
Building initial module for 2.6.32-358.23.2.ali1195.el6.x86_64
configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 2.6.32-358.23.2.ali1195.el6.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.3/build/make.log for more information.
warning: %post(zfs-dkms-0.6.5.3-1.el6.noarch) scriptlet failed, exit status 10
  Installing : spl-0.6.5.3-1.el6.x86_64                                                                                                                                                                                                  7/9 
  Installing : libzfs2-0.6.5.3-1.el6.x86_64                                                                                                                                                                                              8/9 
  Installing : zfs-0.6.5.3-1.el6.x86_64                                                                                                                                                                                                  9/9 

Installed:
  zfs.x86_64 0:0.6.5.3-1.el6                                                                                                                                                                                                                 

Dependency Installed:
  dkms.noarch 0:2.2.0.3-30.git.7c3e7c5.el6 libnvpair1.x86_64 0:0.6.5.3-1.el6 libuutil1.x86_64 0:0.6.5.3-1.el6 libzfs2.x86_64 0:0.6.5.3-1.el6 libzpool2.x86_64 0:0.6.5.3-1.el6 spl.x86_64 0:0.6.5.3-1.el6 spl-dkms.noarch 0:0.6.5.3-1.el6
  zfs-dkms.noarch 0:0.6.5.3-1.el6         

Complete!
```
```
#less /var/lib/dkms/spl/0.6.5.3/build/make.log
......
Making all in module
make[2]: Entering directory `/var/lib/dkms/spl/0.6.5.3/build/module'
make -C /lib/modules/2.6.32-358.23.2.ali1195.el6.x86_64/build SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/kernels/2.6.32-358.23.2.ali1195.el6.x86_64'
  CC [M]  /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-rwlock.o
  CC [M]  /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-vnode.o
In file included from include/linux/io_latency.h:23,
                 from include/linux/blkdev.h:22,
                 from /var/lib/dkms/spl/0.6.5.3/build/include/sys/uio.h:30,
                 from /var/lib/dkms/spl/0.6.5.3/build/include/sys/vnode.h:42,
                 from /var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-vnode.c:28:
include/linux/clocksource.h:249: error: expected ‘;’, ‘,’ or ‘)’ before numeric constant
include/linux/clocksource.h:299: error: expected ‘;’, ‘,’ or ‘)’ before numeric constant
make[5]: *** [/var/lib/dkms/spl/0.6.5.3/build/module/spl/spl-vnode.o] Error 1
make[4]: *** [/var/lib/dkms/spl/0.6.5.3/build/module/spl] Error 2
make[3]: *** [_module_/var/lib/dkms/spl/0.6.5.3/build/module] Error 2
make[3]: Leaving directory `/usr/src/kernels/2.6.32-358.23.2.ali1195.el6.x86_64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.5.3/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/spl/0.6.5.3/build'
make: *** [all] Error 2
```

**Comment by Amitie10g** [comment]
This seems to be a kernel headers issue (and also a very old kernel).
* First, check if you're not using an RT kernel (spl **won't** build with PREEMP_RT patch!)
* If you're sure that you're not using an RT kernel image and headers, check if your distro provides more recent versions of the kernel (3.16 or above)
* Finaly, be sure that the zfs-dkms and spl-dkms versions match

**Comment by PLovertime** [comment]
I am running my fedora21 server and got the same problem when upgrading to 0.6.5.3.
First: Nothing will happen to your data as long as you don't touch or alter partitions etc. It is still there.

This is what I did:
yum remove libzfs2 libzpool2 libuutil1 libnvpair1 zfs-dkms-0.6.5.3 spl-dkms-0.6.5.3 zfs spl

Now you have removed all the previous packages and dependencies.

yum install zfs-dkms-0.6.5.2 spl-dkms-0.6.5.2 spl-0.6.5.2 zfs-0.6.5.2 (the other dependencies will automatically be added)

Now you have zfs support again. You can just run /sbin/modprobe zfs to get the support you need.
#> zpool import "name of pool"
#> zfs list
You'll now see your pool

If you are running a fedora/centos installation I recommend that you also do this:
yum -y install yum-versionlock
yum versionlock zfs zfs-dkms spl spl-dkms libzfs2 libuutil1 libzpool2 libnvpair1

This will ensure that you don't get into the same situation the next time you do yum update.
