### ISSUE TITLE
"Support post-3.13 kthread_create() semantics." breaks 3.13.7 builds on Gentoo with GCC 4.8.2

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/spl#346]
The recently merged 17a527cb0f44cef6582583e502621541061d8817 breaks building on Gentoo with GCC 4.8.2:

```
In file included from /var/tmp/portage/sys-kernel/spl-9999/work/spl-9999/module/spl/../../module/spl/spl-thread.c:27:0:
/var/tmp/portage/sys-kernel/spl-9999/work/spl-9999/module/spl/../../module/spl/spl-thread.c: In function ‘spl_kthread_create’:
/var/tmp/portage/sys-kernel/spl-9999/work/spl-9999/include/sys/thread.h:69:1: error: function ‘spl_kthread_create’ can never be inlined because it uses variable argument lists
 spl_kthread_create(int (*func)(void *), void *data, const char namefmt[], ...)
```
