### ISSUE TITLE
Unable to compile on 3.10-3-rt-amd64

### ISSUE THREAD

**Issue by stefarossi** [zfsonlinux/spl#308]
Hello,

I'm having problems building spl on a 3.10-3-rt-amd64 kernel on Debian testing. I'm using the debian-zfs package from the zfsonlinux repo. I'll attach the complete dkms output, in case it could be useful.

```
# uname -a
Linux lenny 3.10-3-rt-amd64 #1 SMP PREEMPT RT Debian 3.10.11-1 (2013-09-10) x86_64 GNU/Linux
# dkms build spl/0.6.2                  

Kernel preparation unnecessary for this kernel.  Skipping...

Running the pre_build script:
checking for gawk... gawk
checking metadata... META file
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking spl license... GPL
checking linux distribution... debian
checking default package type... deb
checking whether rpm is available... yes (4.11.1)
checking whether rpmbuild is available... yes (4.11.1)
checking whether spec files are available... yes (rpm/generic/*.spec.in)
checking whether dpkg is available... yes (1.16.12)
checking whether dpkg-buildpackage is available... yes (1.16.12.)
checking whether alien is available... yes (8.89)
checking spl config... kernel
checking kernel source directory... /lib/modules/3.10-3-rt-amd64/source
checking kernel build directory... /lib/modules/3.10-3-rt-amd64/build
checking kernel source version... 3.10-3-rt-amd64
checking kernel file name for module symbols... Module.symvers
checking whether debugging is enabled... no
checking whether basic debug logging is enabled... yes
checking whether basic kmem accounting is enabled... yes
checking whether detailed kmem tracking is enabled... no
checking whether modules can be built... yes
checking whether atomic types use spinlocks... no
checking whether kernel defines atomic64_t... yes
checking whether kernel defines atomic64_cmpxchg... yes
checking whether kernel defines atomic64_xchg... yes
checking whether kernel defines uintptr_t... yes
checking whether register_sysctl_table() wants 2 args... no
checking whether set_shrinker() available... no
checking whether shrinker callback wants 3 args... no
checking whether struct path used in struct nameidata... yes
checking whether task_curr() is available... no
checking whether unnumbered sysctl support exists... no
checking whether struct ctl_table has ctl_name... no
checking whether struct vmalloc_info is declared... yes
checking whether PDE_DATA() is available... yes
checking whether fls64() is available... yes
checking whether device_create() is available... yes
checking whether device_create() wants 5 args... yes
checking whether class_device_create() is available... no
checking whether set_normalized_timespec() is available as export... yes
checking whether set_normalized_timespec() is an inline... yes
checking whether timespec_sub() is available... yes
checking whether init_utsname() is available... yes
checking whether header linux/uaccess.h exists... yes
checking whether kmalloc_node() is available... yes
checking whether monotonic_clock() is available... no
checking whether struct inode has i_mutex... yes
checking whether struct mutex has owner... no
checking whether struct mutex owner is a task_struct... no
checking whether mutex_lock_nested() is available... yes
checking whether on_each_cpu() wants 3 args... yes
checking whether kallsyms_lookup_name() is available... yes
checking whether get_vmalloc_info() is available... no
checking whether symbol *_pgdat exist... yes
checking whether first_online_pgdat() is available... no
checking whether next_online_pgdat() is available... no
checking whether next_zone() is available... no
checking whether pgdat_list is available... no
checking whether global_page_state() is available... yes
checking whether page state NR_FREE_PAGES is available... yes
checking whether page state NR_INACTIVE is available... no
checking whether page state NR_INACTIVE_ANON is available... yes
checking whether page state NR_INACTIVE_FILE is available... yes
checking whether page state NR_ACTIVE is available... no
checking whether page state NR_ACTIVE_ANON is available... yes
checking whether page state NR_ACTIVE_FILE is available... yes
checking whether symbol get_zone_counts is needed... no
checking whether user_path_dir() is available... yes
checking whether set_fs_pwd() is available... no
checking whether set_fs_pwd() requires const struct path *... yes
checking whether vfs_unlink() wants 2 args... yes
checking whether vfs_rename() wants 4 args... yes
checking whether vfs_fsync() is available... yes
checking whether vfs_fsync() wants 2 args... yes
checking whether truncate_range() inode operation is available... no
checking whether struct fs_struct uses spinlock_t... yes
checking whether struct cred exists... yes
checking whether kuid_t/kgid_t is available... yes; optional
checking whether groups_search() is available... no
checking whether __put_task_struct() is available... no
checking whether proc_handler() wants 5 args... yes
checking whether kvasprintf() is available... yes
checking whether rwsem_is_locked() acquires sem->wait_lock... no
checking whether fops->fallocate() exists... yes
checking whether iops->fallocate() exists... no
checking whether fops->fallocate() exists... no
checking whether shrink_dcache_memory() is available... no
checking whether shrink_icache_memory() is available... no
checking whether symbol kern_path_parent exists in header... no
checking whether kern_path_parent() is available... no
checking whether symbol kern_path_locked exists in header... yes
checking whether CONFIG_KALLSYMS is defined... yes
checking whether CONFIG_ZLIB_INFLATE is defined... yes
checking whether CONFIG_ZLIB_DEFLATE is defined... yes
checking whether zlib_deflate_workspacesize() wants 2 args... yes
checking whether struct shrink_control exists... yes
checking whether struct rw_semaphore member wait_lock is raw... no
checking whether header linux/sched/rt.h exists... yes
checking whether vfs_getattr() wants... 2 args
configure: creating ./config.status
config.status: creating Makefile
config.status: creating module/Makefile
config.status: creating module/spl/Makefile
config.status: creating module/splat/Makefile
config.status: creating include/Makefile
config.status: creating include/fs/Makefile
config.status: creating include/linux/Makefile
config.status: creating include/rpc/Makefile
config.status: creating include/sharefs/Makefile
config.status: creating include/sys/Makefile
config.status: creating include/sys/fm/Makefile
config.status: creating include/sys/fs/Makefile
config.status: creating include/sys/sysevent/Makefile
config.status: creating include/util/Makefile
config.status: creating include/vm/Makefile
config.status: creating spl.release
config.status: creating spl_config.h
config.status: executing depfiles commands
config.status: executing libtool commands

Building module:
cleaning build area....
make KERNELRELEASE=3.10-3-rt-amd64.......(bad exit status: 2)
Error! Bad return status for module build on kernel: 3.10-3-rt-amd64 (x86_64)
Consult /var/lib/dkms/spl/0.6.2/build/make.log for more information.

#cat /var/lib/dkms/spl/0.6.2/build/make.log
DKMS make.log for spl-0.6.2 for kernel 3.10-3-rt-amd64 (x86_64)
sab  9 nov 2013, 23.55.43, CET
make  all-recursive
make[1]: Entering directory `/var/lib/dkms/spl/0.6.2/build'
Making all in module
make[2]: Entering directory `/var/lib/dkms/spl/0.6.2/build/module'
make -C /lib/modules/3.10-3-rt-amd64/build SUBDIRS=`pwd`  O=/lib/modules/3.10-3-rt-amd64/build CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/linux-headers-3.10-3-rt-amd64'
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-debug.o
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.o
In file included from /var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h:30:0,
                 from /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:27:
/var/lib/dkms/spl/0.6.2/build/include/linux/rwsem_compat.h: In function ‘spl_rwsem_is_locked’:
/var/lib/dkms/spl/0.6.2/build/include/linux/rwsem_compat.h:57:6: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.2/build/include/linux/rwsem_compat.h:59:3: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
In file included from /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:27:0:
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h: In function ‘spl_rw_set_owner’:
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h:55:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h:57:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h: In function ‘spl_rw_clear_owner’:
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h:65:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h:67:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h: In function ‘rw_owner’:
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h:76:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.2/build/include/sys/rwlock.h:78:9: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c: In function ‘__rwsem_wake_one_writer_locked’:
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:56:12: error: ‘struct rw_semaphore’ has no member named ‘activity’
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:58:18: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c: In function ‘__up_read_locked’:
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:73:18: error: ‘struct rw_semaphore’ has no member named ‘activity’
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:73:53: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c: In function ‘__down_write_trylock_locked’:
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:84:16: error: ‘struct rw_semaphore’ has no member named ‘activity’
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:84:50: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.c:85:20: error: ‘struct rw_semaphore’ has no member named ‘activity’
make[7]: *** [/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-rwlock.o] Error 1
make[6]: *** [/var/lib/dkms/spl/0.6.2/build/module/spl] Error 2
make[5]: *** [_module_/var/lib/dkms/spl/0.6.2/build/module] Error 2
make[4]: *** [sub-make] Error 2
make[3]: *** [all] Error 2
make[3]: Leaving directory `/usr/src/linux-headers-3.10-3-rt-amd64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/spl/0.6.2/build'
make: *** [all] Error 2
```
Thanks.

**Comment by behlendorf** [comment]
Closing this is believe to have been fixed in master and is awaiting verification.

**Comment by clefru** [comment]
https://github.com/zfsonlinux/spl/pull/589

**Comment by clefru** [comment]
#589

**Comment by clefru** [comment]
https://github.com/zfsonlinux/spl/commit/a6ae97caed620b0e9e0575346062c751f6f15483 would have fixed the issue if https://github.com/zfsonlinux/spl/commit/f58040c0fc8bc6490fcc75db7fc3e709dfc3c656 would not have reintroduced code that depends on the vanilla kernel implementation of rwsem. As rwsem changes dramatically under PREEMPT_RT_FULL, the last commit broke RT support in spl.

https://github.com/zfsonlinux/spl/pull/589 introduces a rwsem_rt compatible implementation of rwsem_tryupgrade.
