### ISSUE TITLE
SPL can not build on 2.6.39 kernel

### ISSUE THREAD

**Issue by igsbox** [zfsonlinux/spl#39]
I try to compile zfs+spl on Jeremy's kernel 2.6.39-rc3 and receive error:

/tmp/spl-build-root-keyAkN9Q/BUILD/spl-0.6.0/module/spl/../../module/spl/spl-vnode.c:42: error: ‘SPIN_LOCK_UNLOCKED’ undeclared here (not in a function)
/tmp/spl-build-root-keyAkN9Q/BUILD/spl-0.6.0/module/spl/../../module/spl/spl-vnode.c: In function ‘vn_remove’:
/tmp/spl-build-root-keyAkN9Q/BUILD/spl-0.6.0/module/spl/../../module/spl/spl-vnode.c:319: error: implicit declaration of function ‘path_lookup’

As I see in kernel header file linux/spinlock_types.h, SPIN_LOCK_UNLOCKED was deprecated already in 2.6.32 and now in 2.6.39 no such definition exist.
