### ISSUE TITLE
support for recent stable kernels needed.

### ISSUE THREAD

**Issue by seriv** [zfsonlinux/spl#5]
Spl rely on ctl_name in the ctl_table structure in include/linux/sysctl.h which is eliminated starting from 2.6.33 stable (commit 86926d0096279b9739ceeff40f68d3c33b9119a9). 
It does not check if linux kernel has fix for O_DSYNC flag, which was introduced by commit 6b2f3d1f769be5779b479c37800229d9a4809fc3. 
On Fedora 13, with kernel 2.6.33.3-85.fc13 after fixing these 2 problems I run into next one:
{{{
$ make rpm
...
  CC [M]  /tmp/spl-build-seriv-jx6WvnKt/BUILD/spl-0.4.9/module/splat/splat-vnode.o
/tmp/spl-build-seriv-jx6WvnKt/BUILD/spl-0.4.9/module/splat/splat-vnode.c: In function 'fd_uninstall':
/tmp/spl-build-seriv-jx6WvnKt/BUILD/spl-0.4.9/module/splat/splat-vnode.c:427: error: 'struct files_struct' has no member named 'max_fds'
/tmp/spl-build-seriv-jx6WvnKt/BUILD/spl-0.4.9/module/splat/splat-vnode.c:430: error: 'struct files_struct' has no member named 'fd'
/tmp/spl-build-seriv-jx6WvnKt/BUILD/spl-0.4.9/module/splat/splat-vnode.c:434: error: 'struct files_struct' has no member named 'fd'
/tmp/spl-build-seriv-jx6WvnKt/BUILD/spl-0.4.9/module/splat/splat-vnode.c:435: error: 'struct files_struct' has no member named 'close_on_exec'
...
}}}
I don't know how to fix it.
