### ISSUE TITLE
Can't dkms install spl (Fedora 18 3.9.6, 3.9.11)

### ISSUE THREAD

**Issue by PavelLeon** [zfsonlinux/spl#270]
On Fedora 18 x64, had ZFSon Linux working.
// Linux falkner 3.9.6-200.fc18.x86_64 #1 SMP Thu Jun 13 18:56:55 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
// ZoL : 0.6.1

Until tried to update kernel 3.9.11. Then ZoL broke (dkms status -> spl,zfs : added)

Rolled back to 3.6.9, but on dkms install still hitting same problem as in 3.9.11.

dkms remove -m zfs -v 0.6.1 --all
... Done.

dkms remove -m spl -v 0.6.1 --all
... Done.

dkms add -m spl -v 0.6.1
... DKMS: add completed.

dkms install -m spl -v 0.6.1
...
Building module:
cleaning build area...
make KERNELRELEASE=3.9.6-200.fc18.x86_64...(bad exit status: 2)
Error! Bad return status for module build on kernel: 3.9.6-200.fc18.x86_64 (x86_64)
Consult /var/lib/dkms/spl/0.6.1/build/make.log for more information.

 tail -30 /var/lib/dkms/spl/0.6.1/build/make.log

[root@falkner ~]# tail -15 /var/lib/dkms/spl/0.6.1/build/make.log
/usr/src/kernels/3.9.6-200.fc18.x86_64/arch/x86/include/asm/paravirt.h:833: warning: asm operand 2 probably doesn't match constraints
/usr/src/kernels/3.9.6-200.fc18.x86_64/arch/x86/include/asm/paravirt.h:838: error: impossible constraint in `asm'
/usr/src/kernels/3.9.6-200.fc18.x86_64/arch/x86/include/asm/paravirt.h:843: error: impossible constraint in`asm'
/usr/src/kernels/3.9.6-200.fc18.x86_64/arch/x86/include/asm/paravirt.h:838: error: impossible constraint in `asm'
/usr/src/kernels/3.9.6-200.fc18.x86_64/arch/x86/include/asm/paravirt.h:833: error: impossible constraint in`asm'
/usr/src/kernels/3.9.6-200.fc18.x86_64/arch/x86/include/asm/paravirt.h:833: error: impossible constraint in `asm'
make[5]: *** [/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-kmem.o] Error 1
make[4]: *** [/var/lib/dkms/spl/0.6.1/build/module/spl] Error 2
make[3]: *** [_module_/var/lib/dkms/spl/0.6.1/build/module] Error 2
make[3]: Leaving directory`/usr/src/kernels/3.9.6-200.fc18.x86_64'
make[2]: **\* [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.1/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/var/lib/dkms/spl/0.6.1/build'
make: **\* [all] Error 2
## /usr/src/kernels/3.9.6-200.fc18.x86_64/arch/x86/include/asm/paravirt.h [831- ]:

static inline notrace void arch_local_irq_restore(unsigned long f)
{
        PVOP_VCALLEE1(pv_irq_ops.restore_fl, f);
## }

regards
- Pablo
