### ISSUE TITLE
spl-dkms doesn't build because SPL_AC_RWSEM_SPINLOCK_IS_RAW yields false negative

### ISSUE THREAD

**Issue by vain** [zfsonlinux/spl#619]
Arch Linux, linux-lts 4.9.30-1, using spl-dkms from AUR. I get a DKMS build failure:
```
(1/2) Install DKMS modules
==> dkms install spl/0.6.5.9 -k 4.9.30-1-lts
Error! Bad return status for module build on kernel: 4.9.30-1-lts (x86_64)
Consult /var/lib/dkms/spl/0.6.5.9/build/make.log for more information.
```

I think the important parts of `make.log` and `config.log` are those:
```
./include/linux/spinlock.h:289:40: note: expected ‘spinlock_t * {aka struct spinlock *}’ but argument is of type ‘raw_spinlock_t * {aka struct raw_spinlock *}’
```
```
configure:14520: checking whether struct rw_semaphore member wait_lock is raw
configure:14551: cp conftest.c build && make modules -C /usr/lib/modules/4.9.30-1-lts/build EXTRA_CFLAGS=-Werror-implicit-function-declaration -Werror  M=/var/lib/dkms/spl/0.6.5.9/build/build 
/var/lib/dkms/spl/0.6.5.9/build/build/conftest.c: In function ‘main’:
/var/lib/dkms/spl/0.6.5.9/build/build/conftest.c:52:29: error: ‘dummy_lock’ is used uninitialized in this function [-Werror=uninitialized]
   dummy_semaphore.wait_lock = dummy_lock;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [scripts/Makefile.build:300: /var/lib/dkms/spl/0.6.5.9/build/build/conftest.o] Error 1
make: *** [Makefile:1490: _module_/var/lib/dkms/spl/0.6.5.9/build/build] Error 2
configure:14554: $? = 2
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "spl"
| #define PACKAGE_TARNAME "spl"
| #define PACKAGE_VERSION "0.6.5.9"
| #define PACKAGE_STRING "spl 0.6.5.9"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define SPL_META_NAME "spl"
| #define SPL_META_VERSION "0.6.5.9"
| #define SPL_META_RELEASE "1"
| #define SPL_META_LICENSE "GPL"
| #define SPL_META_ALIAS "spl-0.6.5.9-1"
| #define SPL_META_AUTHOR "OpenZFS on Linux"
| #define PACKAGE "spl"
| #define VERSION "0.6.5.9"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define SPL_IS_GPL_COMPATIBLE 1
| #define HAVE_ATOMIC64_T 1
| #define HAVE_SPLIT_SHRINKER_CALLBACK 1
| #define HAVE_PDE_DATA 1
| #define HAVE_SET_FS_PWD_WITH_CONST 1
| #define HAVE_3ARGS_VFS_UNLINK 1
| #define HAVE_6ARGS_VFS_RENAME 1
| #define HAVE_2ARGS_VFS_FSYNC 1
| #define HAVE_FS_STRUCT_SPINLOCK 1
| #define HAVE_KUIDGID_T 1
| #define HAVE_PUT_TASK_STRUCT 1
| #define HAVE_FILE_FALLOCATE 1
| #define HAVE_2ARGS_ZLIB_DEFLATE_WORKSPACESIZE 1
| #define HAVE_SHRINK_CONTROL_STRUCT 1
| 
| 
| 		#include <linux/rwsem.h>
| 
| int
| main (void)
| {
| 
| 		struct rw_semaphore dummy_semaphore __attribute__ ((unused));
| 		raw_spinlock_t dummy_lock __attribute__ ((unused));
| 		dummy_semaphore.wait_lock = dummy_lock;
| 
|   ;
|   return 0;
| }
| 
configure:14572: result: no
```

IIUC, the point of this check is to see whether `dummy_semaphore.wait_lock` is of type `spinlock_t` or `raw_spinlock_t`, so the compiler issuing a warning/error because `dummy_lock` is uninitialized leads to a false negative.

When using GCC, changing
```
raw_spinlock_t dummy_lock __attribute__ ((unused));
```
to
```
raw_spinlock_t dummy_lock __attribute__ ((unused)) = {0};
```
initializes that struct with zeroes which makes the (misleading) warning go away. spl-dkms and zfs-dkms happily compile. I'm not up for experiments here :), so I won't import my pool with these "patched" modules. If anyone could confirm that my analysis is correct and that the workaround is good enough, I'd appreciate that.

Full log files are available here: https://gist.github.com/vain/aa9c0ee01bbd77d2c40104e5c8472dc7

**Comment by RJVB** [comment]
Funny, I got a very comparable error when installing SPL0.65.9 with dkms on Linux 4.9.30, using GCC 7.1.0 .  Specifically, it was a warning-turned-into-error on line 55 of include/sys/rwlock.h about passing  the first argument of spl_rwsem_lock_irqsave() from an incompatible pointer (I lost the exact wording but not its message).

On a hunch I pointed /usr/bin/gcc to gcc 6.3.0 instead of to the very recent gcc 7.1.0 install, and then the `dkms install spl/0.6.5.9 -k 4.9.30` completed without error.

Is this just gc 7.1.0 being more pedantic than the gcc 6 series or does it actually have a point in warning about that function call?

ZFS builds fine with GCC 7.1.0

**Comment by vain** [comment]
Just for the record, so people don't have to search through my logs to find this: Yes, I'm using gcc 7.1.1. (clang 4.0 warns about uninitialized structs as well, though.)

> Is this just gc 7.1.0 being more pedantic than the gcc 6 series or does it actually have a point in warning about that function call?

The function call is using an incompatible pointer and that's wrong, but it's only doing that because the configure script told it to do so. That's the actual problem (at least in my case). :-)

**Comment by RJVB** [comment]
On Monday June 05 2017 11:24:32 vain wrote:

>>clang 4.0 warns about uninitialized structs as well, though.)

Is there any benefit to using clang, btw?

>> Is this just gc 7.1.0 being more pedantic than the gcc 6 series or does it actually have a point in warning about that function call?
>
>The function call is using an incompatible pointer and that's wrong, but it's only doing that because the configure script told it to do so. That's the actual problem (at least in my case). :-)

The configure script told "it" to use an incompatible pointer, or to complain about the same pointer that's also used with earlier gcc versions?

**Comment by vain** [comment]
> Is there any benefit to using clang, btw?

For ZFS? No idea.

> The configure script told "it" to use an incompatible pointer, or to complain about the same pointer that's also used with earlier gcc versions?

The former. Sorry for being unclear.

Here's the part of the configure process that tries to determine the correct type to use: https://github.com/zfsonlinux/spl/blob/master/config/spl-build.m4#L1302 It tries to compile a little C program and checks for errors during compilation. As `-Werror` is being used, warnings are treated as errors. As you can see in my initial comment, gcc 7 complains that `dummy_lock` is being used uninitialized -- and that results in an error due to `-Werror`. But there is *no* error regarding the type of `dummy_lock`.

The configure process expects compilation to fail if -- and only if -- the types of `dummy_semaphore.wait_lock` and `dummy_lock` don't match. Compilation fails, yes, but it fails for another reason, so the configure process comes to the wrong conclusion. As a result, a wrong pointer type is being used in SPL (which then fails later during the actual compilation).

I don't have a gcc 6 at hand, I only have gcc 5 ready (on Ubuntu 16.04). Let's take the following example:

```
typedef struct inner
{
    char x, y, z;
} inner_t;

typedef struct outer
{
    int a, b, c;
    inner_t inner;
} outer_t;

int
main()
{
    outer_t o __attribute__ ((unused));
    inner_t i __attribute__ ((unused));

    o.inner = i;

    return 0;
}
```

Try to compile this using `gcc -Wall -Wextra -o bla bla.c`. gcc 5 does *not* issue a warning about `i` being uninitialized, but gcc 7 does.

Maybe you could try to verify this using gcc 6? Does it print a warning?

(I couldn't find any hints in the [gcc 7 changelog](https://gcc.gnu.org/gcc-7/changes.html) on this issue ...)

**Comment by RJVB** [comment]
On Wednesday June 07 2017 11:22:19 vain wrote:

>Compilation fails, yes, but it fails for another reason, so the configure process comes to the wrong conclusion.

Ahh, that kind of issue. Annoying (and not necessarily trivial to fix), but less so than a hitherto undetected issue in the source!

>I don't have a gcc 6 at hand, I only have gcc 5 ready (on Ubuntu 16.04). Let's take the following example:

I get mine from the ubuntu-toolchain-r PPA.

>Maybe you could try to verify this using gcc 6? Does it print a warning?

Indeed, gcc 6.3 succeeds without as much as a warning.

**Comment by behlendorf** [comment]
Closing.  This was resolved by 7a35f2b49581894cde93c356fd9372ff3246d344.  On the larger point on individual configure checks potentially misidentifying an interface, patches are always welcome to improve them.
