### ISSUE TITLE
doesn't compile on 2.6.18-xen

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/spl#50]
make[2]: Entering directory `/tmp/spl/scripts'
make[2]: Nothing to be done for`all'.
make[2]: Leaving directory `/tmp/spl/scripts'
Making all in module
make[2]: Entering directory`/tmp/spl/module'
make -C /tmp/xen-3.1.0-src-ec2-v1.4/build-linux-2.6.18-xen_x86_64/ SUBDIRS=`pwd`  O=/tmp/xen-3.1.0-src-ec2-v1.4/build-linux-2.6.18-xen_x86_64/ modules
make[3]: Entering directory `/tmp/xen-3.1.0-src-ec2-v1.4/build-linux-2.6.18-xen_x86_64'
make -C /tmp/xen-3.1.0-src-ec2-v1.4/linux-2.6.18-xen O=/tmp/xen-3.1.0-src-ec2-v1.4/build-linux-2.6.18-xen_x86_64 modules
  CC [M]  /tmp/spl/module/spl/../../module/spl/spl-debug.o
  CC [M]  /tmp/spl/module/spl/../../module/spl/spl-proc.o
  CC [M]  /tmp/spl/module/spl/../../module/spl/spl-kmem.o
  CC [M]  /tmp/spl/module/spl/../../module/spl/spl-thread.o
  CC [M]  /tmp/spl/module/spl/../../module/spl/spl-taskq.o
  CC [M]  /tmp/spl/module/spl/../../module/spl/spl-rwlock.o
  CC [M]  /tmp/spl/module/spl/../../module/spl/spl-vnode.o
/tmp/spl/module/spl/../../module/spl/spl-vnode.c: In function 'vn_set_pwd':
/tmp/spl/module/spl/../../module/spl/spl-vnode.c:732: error: 'LOOKUP_CHDIR' undeclared (first use in this function)
/tmp/spl/module/spl/../../module/spl/spl-vnode.c:732: error: (Each undeclared identifier is reported only once
/tmp/spl/module/spl/../../module/spl/spl-vnode.c:732: error: for each function it appears in.)
make[7]: *** [/tmp/spl/module/spl/../../module/spl/spl-vnode.o] Error 1
make[6]: *** [/tmp/spl/module/spl] Error 2
make[5]: *** [_module_/tmp/spl/module] Error 2
make[4]: *** [modules] Error 2
make[3]: *** [modules] Error 2
make[3]: Leaving directory`/tmp/xen-3.1.0-src-ec2-v1.4/build-linux-2.6.18-xen_x86_64'
make[2]: **\* [modules] Error 2
make[2]: Leaving directory `/tmp/spl/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/tmp/spl'
make: **\* [all] Error 2
