### ISSUE TITLE
doesn't compile on 3.1.0vanilla

### ISSUE THREAD

**Issue by Rudd-O** [zfsonlinux/spl#52]
make -C /home/rudd-o/Projects/Third-party/linux/karen.dragonfear SUBDIRS=`pwd`  modules
make[3]: Entering directory `/home/rudd-o/Projects/Third-party/linux/karen.dragonfear'
  CC [M]  /home/rudd-o/Projects/Third-party/spl/module/spl/../../module/spl/spl-debug.o
  CC [M]  /home/rudd-o/Projects/Third-party/spl/module/spl/../../module/spl/spl-proc.o
  CC [M]  /home/rudd-o/Projects/Third-party/spl/module/splat/../../module/splat/splat-ctl.o
/home/rudd-o/Projects/Third-party/spl/module/spl/../../module/spl/spl-debug.c: In function ‘spl_debug_dump_all_pages’:
/home/rudd-o/Projects/Third-party/spl/module/spl/../../module/spl/spl-debug.c:963:9: error: too few arguments to function ‘filp->f_op->fsync’
make[5]: **\* [/home/rudd-o/Projects/Third-party/spl/module/spl/../../module/spl/spl-debug.o] Error 1
make[5]: **\* Waiting for unfinished jobs....

woops.
