### ISSUE TITLE
spl-dkms does not build on kernel 3.12.6

### ISSUE THREAD

**Issue by mir07** [zfsonlinux/spl#323]
Newest kernel in Debian Sid is 3.12.6-1 which is rulling out to Sid. Problem is that spl-dkms does not build with this kernel. See make log below:
DKMS make.log for spl-0.6.2 for kernel 3.12-1-amd64 (x86_64)
lør dec 28 12:39:05 CET 2013
make  all-recursive
make[1]: Entering directory `/var/lib/dkms/spl/0.6.2/build'
Making all in module
make[2]: Entering directory`/var/lib/dkms/spl/0.6.2/build/module'
make -C /lib/modules/3.12-1-amd64/build SUBDIRS=`pwd`  O=/lib/modules/3.12-1-amd64/build CONFIG_SPL=m modules
make[3]: Entering directory `/usr/src/linux-headers-3.12-1-amd64'
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-debug.o
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-kmem.o
In file included from /var/lib/dkms/spl/0.6.2/build/include/sys/types.h:44:0,
                 from /var/lib/dkms/spl/0.6.2/build/include/sys/kmem.h:37,
                 from /var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-kmem.c:27:
/var/lib/dkms/spl/0.6.2/build/include/linux/mm_compat.h:198:16: error: unknown field ‘shrink’ specified in initializer
  static struct shrinker s = {                                   \
                ^
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-kmem.c:842:1: note: in expansion of macro ‘SPL_SHRINKER_DECLARE’
 SPL_SHRINKER_DECLARE(spl_kmem_cache_shrinker,
 ^
/var/lib/dkms/spl/0.6.2/build/include/linux/mm_compat.h:198:16: warning: initialization from incompatible pointer type [enabled by default]
  static struct shrinker s = {                                   \
                ^
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-kmem.c:842:1: note: in expansion of macro ‘SPL_SHRINKER_DECLARE’
 SPL_SHRINKER_DECLARE(spl_kmem_cache_shrinker,
 ^
/var/lib/dkms/spl/0.6.2/build/include/linux/mm_compat.h:198:16: warning: (near initialization for ‘spl_kmem_cache_shrinker.count_objects’) [enabled by default]
  static struct shrinker s = {                                   \
                ^
/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-kmem.c:842:1: note: in expansion of macro ‘SPL_SHRINKER_DECLARE’
 SPL_SHRINKER_DECLARE(spl_kmem_cache_shrinker,
 ^
make[7]: *** [/var/lib/dkms/spl/0.6.2/build/module/spl/../../module/spl/spl-kmem.o] Error 1
make[6]: *** [/var/lib/dkms/spl/0.6.2/build/module/spl] Error 2
make[5]: *** [_module_/var/lib/dkms/spl/0.6.2/build/module] Error 2
make[4]: *** [sub-make] Error 2
make[3]: *** [all] Error 2
make[3]: Leaving directory`/usr/src/linux-headers-3.12-1-amd64'
make[2]: **\* [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/spl/0.6.2/build/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/var/lib/dkms/spl/0.6.2/build'
make: **\* [all] Error 2
