### ISSUE TITLE
SL 2.6.32-358.11.1.el6.x86_64 namespace collision installing spl-dkms-0.6.4-1.el6

### ISSUE THREAD

**Issue by SETIguy** [zfsonlinux/spl#451]
spl-dkms fails to install 

<pre>
Building for 2.6.32-358.11.1.el6.x86_64
Building initial module for 2.6.32-358.11.1.el6.x86_64
Error! Bad return status for module build on kernel: 2.6.32-358.11.1.el6.x86_64 (x86_64)
Consult /var/lib/dkms/spl/0.6.4/build/make.log for more information.
</pre>

The interesting lines from make.log are...
<pre>
  CC [M]  /var/lib/dkms/spl/0.6.4/build/module/splat/../../module/splat/splat-ctl.o
In file included from include/linux/fs.h:424,
                 from /var/lib/dkms/spl/0.6.4/build/module/splat/../../module/splat/splat-ctl.c:50:
include/linux/percpu-rwsem.h:89:20: error: macro "mutex_init" requires 4 arguments, but only 1 given
In file included from include/linux/fs.h:424,
                 from /var/lib/dkms/spl/0.6.4/build/module/splat/../../module/splat/splat-ctl.c:50:
include/linux/percpu-rwsem.h: In function ‘percpu_init_rwsem’:
include/linux/percpu-rwsem.h:89: error: ‘mutex_init’ undeclared (first use in this function)
include/linux/percpu-rwsem.h:89: error: (Each undeclared identifier is reported only once
include/linux/percpu-rwsem.h:89: error: for each function it appears in.)
make[5]: *** [/var/lib/dkms/spl/0.6.4/build/module/splat/../../module/splat/splat-ctl.o] Error 1
make[4]: *** [/var/lib/dkms/spl/0.6.4/build/module/splat] Error 2
</pre>

**Comment by behlendorf** [comment]
Closing.  Unable to reproduce.
