### ISSUE TITLE
spl-dkms ubuntu package missing dependency on libc6-dev

### ISSUE THREAD

**Issue by jefft** [zfsonlinux/spl#518]
(Note: This should be reported on the pkg-spl project but issue tracking isn't enabled there).

On a clean system (e.g. Mint 17.3 live CD) the spl-dkms package fails to compile:

```
mint ~ # apt-add-repository --yes ppa:zfs-native/stable
mint ~ # apt-get update
mint ~ # apt-get install spl-dkms
Reading package lists... Done
Building dependency tree      
Reading state information... Done
The following NEW packages will be installed:
  spl-dkms
0 upgraded, 1 newly installed, 0 to remove and 123 not upgraded.
Need to get 0 B/368 kB of archives.
After this operation, 2,821 kB of additional disk space will be used.
Selecting previously unselected package spl-dkms.
(Reading database ... 163641 files and directories currently installed.)
Preparing to unpack .../spl-dkms_0.6.5.3-1~trusty_all.deb ...
Unpacking spl-dkms (0.6.5.3-1~trusty) ...
Setting up spl-dkms (0.6.5.3-1~trusty) ...
Loading new spl-0.6.5.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.19.0-32-generic
Building initial module for 3.19.0-32-generic
configure: error: in `/var/lib/dkms/spl/0.6.5.3/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
Error! Bad return status for module build on kernel: 3.19.0-32-generic (x86_64)
Consult /var/lib/dkms/spl/0.6.5.3/build/make.log for more information.
```

and /var/lib/dkms/spl/0.6.5.3/build/config.log contains (amongst other things):

```
configure:3400: $? = 4
configure:3420: checking whether the C compiler works
configure:3442: gcc    conftest.c  >&5
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
configure:3446: $? = 1
configure:3484: result: no
...
configure:3489: error: in `/var/lib/dkms/spl/0.6.5.3/build':
configure:3491: error: C compiler cannot create executables
See `config.log' for more details
```

Installing package libc6-dev-bin beforehand gets it working.

There are two bugs here actually: first, that libc6-dev is missing as a dependency, and secondly that the spl-dkms claims to be successfully installed even if its compilation failed. 

```
mint ~ # dpkg -l | grep spl-dkms
ii  spl-dkms                                    0.6.5.3-1~trusty                                    all          Solaris Porting Layer kernel modules for Linux
```

That then leaves one confused as to why `modprobe zfs` fails.

I notice that `build-essential` is a Recommends. Perhaps it needs to be made a full dependency?

**Comment by behlendorf** [comment]
Closing.  The spl packages have been retired.
