### ISSUE TITLE
SPL does not compile with 3.16.5 gentoo kernel.

### ISSUE THREAD

**Issue by janlam7** [zfsonlinux/spl#413]
The latest spl (commit 52479ecf58fa89190e384edcf838fecccc786af5) does not compile with gentoo-sources 3.16.5 on my machine.

The lines with errors are these 2:

In file included from /var/tmp/portage/sys-kernel/spl-9999/work/spl-9999/module/spl/../../module/spl/spl-debug.c:39:0:
/var/tmp/portage/sys-kernel/spl-9999/work/spl-9999/module/spl/../../module/spl/spl-debug.c: In function 'trace_max_debug_mb':
/var/tmp/portage/sys-kernel/spl-9999/work/spl-9999/module/spl/../../module/spl/spl-debug.c:551:27: error: 'num_physpages' undeclared (first use in this function)

and

/var/tmp/portage/sys-kernel/spl-9999/work/spl-9999/module/spl/../../module/spl/spl-debug.c: In function 'spl_debug_init':
/var/tmp/portage/sys-kernel/spl-9999/work/spl-9999/module/spl/../../module/spl/spl-debug.c:1191:20: error: 'num_physpages' undeclared (first use in this function)
